include_directories(${CMAKE_CURRENT_LIST_DIR})

if (NOT DEFINED XSHORTCUTS_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/../XShortcuts/xshortcuts.cmake)
    set(XREGIONSWIDGET_SOURCES ${XREGIONSWIDGET_SOURCES} ${XSHORTCUTS_SOURCES})
endif()
