include_directories(${CMAKE_CURRENT_LIST_DIR})

if (NOT DEFINED XINFODB_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/../XInfoDB/xinfodb.cmake)
    set(XREGIONSMODEL_SOURCES ${XREGIONSMODEL_SOURCES} ${XINFODB_SOURCES})
endif()

set(XREGIONSMODEL_SOURCES
    ${XREGIONSMODEL_SOURCES}
    ${CMAKE_CURRENT_LIST_DIR}/xregionitem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xregionitem.h
    ${CMAKE_CURRENT_LIST_DIR}/xregionsmodel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xregionsmodel.h
)
